name: 'Automated Nuget Publishing'

on:
  push:
    tags:
      - 'v*'

env:
  DOTNET_VERSION: '7.0.x'
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  PROJECT_PATH: './CryptoWatch.REST.API/CryptoWatch.REST.API.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output

jobs:
  build:

    name: automated-nuget-publishing-${{matrix.os}}
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Restore dependencies'
        run: dotnet restore
      - name: 'Get Version'
        id: get_version
        uses: battila7/get-version-tag@v2
      - name: 'Pack'
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
      - name: 'Push'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg --api-key ${{ secrets.NUGET_API }} --source ${{ env.NUGET_SOURCE_URL }} --skip-duplicate
